name: .NET

on:
  pull_request:
    branches:
      - development
      - main

jobs:
#  build:
#    runs-on: 
#      - self-hosted
#      - windows
#
#    steps:
#    - uses: actions/checkout@v4
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v4
#      with:
#        dotnet-version: 9.0.x
#    - name: Restore dependencies
#      run: dotnet restore
#    - name: Build
#      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
  
  sonar:
    runs-on:
      - self-hosted
      - windows

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: SonarQube Scan
        run: |
          dotnet tool install --global dotnet-sonarscanner
          echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
          dotnet sonarscanner begin `
          /k:"ApiTemplate" `
          /d:sonar.host.url="${{ vars.SONAR_HOST_URL }}" `
          /d:sonar.login="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.cs.opencover.reportsPaths="**\coverage.cobertura.xml"
          
          dotnet build ApiTemplate.sln
          dotnet test Tests/Tests.csproj --no-build --collect:"XPlat Code Coverage"
          
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
