name: Docker Image CI for GHCR

on:
  push:
    branches:
      - development
      - stage
      - main

jobs:
  build_and_publish:
    runs-on:
      - self-hosted
      - windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_LOGIN }}" --password-stdin
  
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_LOGIN }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./API/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

        
